src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'string', length: 255)]
    private $carrierName;

    #[ORM\Column(type: 'string', length: 255)]
    private $carrierPrice;

    #[ORM\Column(type: 'text')]
    private $delivery;

    #[ORM\OneToMany(mappedBy: 'bindedOrder', targetEntity: OrderDetails::class)]
    private $orderDetails;

    #[ORM\Column(type: 'string', length: 255)]
    private $reference;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $stripeSession;

    #[ORM\Column(type: 'integer')]
    private $state;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): self
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?string
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(string $carrierPrice): self
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): self
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection|OrderDetails[]
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOderDetail(OrderDetails $oderDetail): self
    {
        if (!$this->orderDetails->contains($oderDetail)) {
            $this->orderDetails[] = $oderDetail;
            $oderDetail->setBindedOrder($this);
        }

        return $this;
    }

    public function removeOderDetail(OrderDetails $oderDetail): self
    {
        if ($this->orderDetails->removeElement($oderDetail)) {
            // set the owning side to null (unless already changed)
            if ($oderDetail->getBindedOrder() === $this) {
                $oderDetail->setBindedOrder(null);
            }
        }

        return $this;
    }

    public function getTotal():float
    {
        $total = 0;
        foreach ($this->getOrderDetails() as $product) {
            $total += $product->getTotal();
        }
        return $total;
  
    }

    public function getTotalQuantity():float
    {
        $total = 0;
        foreach ($this->getOrderDetails() as $product) {
            $total += $product->getQuantity();
        }
        return $total;
  
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getStripeSession(): ?string
    {
        return $this->stripeSession;
    }

    public function setStripeSession(?string $stripeSession): self
    {
        $this->stripeSession = $stripeSession;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }
}

src/Controller/AccountController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\ChangePasswordType;
use App\Repository\OrderRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Espace membre (sécurisé)
 */
class AccountController extends AbstractController
{
    #[Route('/compte', name: 'account')]
    public function index(): Response
    {
        return $this->render('account/index.html.twig', [
        ]);
    }

    /**
     * Permet la modification du mot de passe d'un utilisateur sur une page dédiée
     */
    #[Route('/compte/mot-de-passe', name: 'account_password')]
    public function changePassword(Request $request, UserPasswordHasherInterface $passwordHasher, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(ChangePasswordType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $old_password = $form->get('old_password')->getData();
            $new_password = $form->get('new_password')->getData();
            $isOldPasswordValid = $passwordHasher->isPasswordValid($user, $old_password);
            if ($isOldPasswordValid) {
                $password = $passwordHasher->hashPassword($user,$new_password);
                $user->setPassword($password);
                $em->flush();
                $this->addFlash(
                    'notice', 
                    'Mot de passe modifié :)'
                );
                return $this->redirectToRoute('account');
            } else {
                $this->addFlash(
                    'notice', 
                    'Mot de passe actuel erroné :('
                );
            }
        }

        return $this->renderForm('account/password.html.twig', [
            'form' => $form
        ]);
    }

    /**
     * Affiche la vue de toutes les commandes d'un utilisateur
     */
    #[Route('/compte/commandes', name: 'account_orders')]
    public function showOrders(OrderRepository $repository): Response
    {
        $orders = $repository->findPaidOrdersByUser($this->getUser());
        return $this->render('account/orders.html.twig', [
            'orders' => $orders
        ]);
    }

    /**
     * Affiche une commande
     */
    #[Route('/compte/commandes/{reference}', name: 'account_order')]
    public function showOrder(Order $order): Response
    {
        if (!$order || $order->getUser() != $this->getUser()) {
            throw $this->createNotFoundException('Commande innaccessible');
        }
        return $this->render('account/order.html.twig', [
            'order' => $order
        ]);
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


/**
 * make:auth utilisé pour la connexion
 */
class SecurityController extends AbstractController
{
    /**
     * @Route("/connexion", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('account');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/account/address.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes adresses - La Boot'Ique'{% endblock %}

{% block body %}
    <a href="{{ path('account_address_new') }}" class="btn btn-info btn-sm float-right mt-2">Ajouter une adresse</a>
    <h2>Gérer mes adresses</h2>

    <div class="row mt-3">
        {% for address in app.user.addresses %}
            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ address.name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted"></h6>
                        <p class="card-text">
                            {{ address.address }},<br>
                            {{ address.postal }} -
                            {{ address.city }}<br>
                            {{ address.country }}
                        </p>
                        <a href="{{ path('account_address_update', {id: address.id}) }}" class="card-link">Modifier</a>
                        <a href="{{ path('account_address_delete', {id: address.id}) }}" class="card-link">Supprimer</a>
                    </div>
                </div>
            </div>
        {% else %}
        <p>
            Vous n'avez ajouté aucune adresse pour le moment.
        </p>
    {% endfor %}
    </div>
    <a title="Retour vers votre espace membres"href="{{ path('account') }}">Retourner à mon compte</a>
{% endblock %}

templates/security/account/address_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes adresses - La Boot'Ique'{% endblock %}

{% block body %}
    <h2 class="mb-4">Enregistrer une addresse</h2>
    {{form_start(form)}}
    <div class="row">
        <div class="col-md-12">{{form_row(form.name)}}</div>
        <div class="col-md-6">{{form_row(form.firstname)}}</div>
        <div class="col-md-6">{{form_row(form.lastname)}}</div>
        <div class="col-md-6">{{form_row(form.address)}}</div>
        <div class="col-md-6">{{form_row(form.postal)}}</div>
        <div class="col-md-6">{{form_row(form.city)}}</div>
        <div class="col-md-6">{{form_row(form.country)}}</div>
        <div class="col-md-6">{{form_row(form.phone)}}</div>
        <div class="col-md-6">{{form_row(form.company)}}</div>
        <div class="col-md-12">{{form_row(form.submit)}}</div>
    </div>

    {{form_end(form)}}
    <a title="Retour vers votre espace membres"href="{{ path('account') }}">Retourner à mon compte</a>
{% endblock %}

templates/security/account/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte - La Boot'Ique{% endblock %}

{% block body %}
    <h2>Mon compte</h2>
    Bienvenue dans votre espace membre {{ app.user.firstname }}.
    <hr>
    {% for message in app.flashes('notice') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="list-group">
        {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('admin') }}" class="list-group-item list-group-item-action">
            Back office
        </a> 
        {% endif %}
        <a href="{{ path('account_orders') }}" class="list-group-item list-group-item-action">
            Mes commandes
        </a>
        <a href="{{ path('account_address') }}" class="list-group-item list-group-item-action">
            Gérer mes adresses
        </a>
        <a href="{{ path('account_password') }}" class="list-group-item list-group-item-action">
            Modifier mot de passe
        </a>
    </div>


{% endblock %}

templates/security/account/order.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma commande - La Boot'Ique'{% endblock %}

{% block body %}
    <h2>Commande n° {{order.reference}}</h2>
    <hr>
    <p>
        <b>Commande passée le :</b> {{order.createdAt|date('d/m/Y')}} <br>
        <b>Statut:</b> {{
            order.state == 1 ? 'Paiment accepté' :
            order.state == 2 ? 'En préparation' : 'Expédiée'
        }}<br>
        <b>Référence : </b><span>{{order.reference}}</span><br>
        <b>Transporteur:</b> {{order.carrierName}}<br>
    </p>
    <table class="table mt-4">
    <thead>
        <tr>
            <th scope="col">Article</th>
            <th scope="col">Quantité</th>
            <th scope="col">Prix unitaire </th>
            <th scope="col">Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for product in order.orderDetails %}
            <tr>
                <td>{{product.product}}</td>
                <td>x{{product.quantity}}</td>
                <td>{{(product.price / 100)|number_format(2,',','.') }} €</td>
                <td>{{(product.total / 100)|number_format(2,',','.') }} €</td>
            </tr>  
        {% endfor %}
            <tr>
                <th>Sous-total</th>
                <td></td>
                <td></td>
                <td>{{(order.total / 100)|number_format(2,',','.') }} €</td>
            </tr>
    </tbody>
</table>
    <div class="text-right">
        <b>Livraison :</b> {{(order.carrierPrice / 100)|number_format(2,',','.') }} €<br>
        <b>Total : </b> {{((order.carrierPrice + order.total) / 100)|number_format(2,',','.') }} €
    </div>
    <a title="Retour vers votre espace membres"href="{{ path('account') }}">Retourner à mon compte</a>
{% endblock %}

templates/security/account/orders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes - La Boot'Ique'{% endblock %}

{% block body %}
    <h2>Voir mes commandes</h2>
    {% if orders %}
        <table class="table mt-4">
            <thead>
                <tr>
                    <th scope="col">Articles</th>
                    <th scope="col">Statut</th>
                    <th scope="col">Total</th>
                    <th scope="col">Passée le </th>
                    <th scope="col">Référence</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{order.totalQuantity}}</td>
                        <td>{{
                            order.state == 1 ? 'Paiment accepté' :
                            order.state == 2 ? 'En préparation' : 'Expédiée'
                        }}</td>
                        <td>{{((order.carrierPrice + order.total) / 100)|number_format(2,',','.') }} €</td>
                        <td>{{order.createdAt|date('d/m/Y')}}</td>
                        <td><span class="badge badge-secondary">{{order.reference}}</span></td>
                        <td><a href="{{ path('account_order', {'reference' : order.reference}) }}">Consulter commande</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Vous n'avez effectué aucune commande pour le moment.</p>        
    {% endif %}
    <a title="Retour vers votre espace membres"href="{{ path('account') }}">Retourner à mon compte</a>
{% endblock %}

templates/security/account/password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mot de passe  - La Boot'Ique{% endblock %}
{% block body %}
    <h2>Modification mot de passe</h2>
    {{form(form)}}
    {% for message in app.flashes('notice') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    <a title="Retour vers votre espace membres"href="{{ path('account') }}">Retourner à mon compte</a>
{% endblock %}